
server:
  port: 8081
  
spring:
  application:
    name: client-service-1
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
      